/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IVestingInterface extends ethers.utils.Interface {
  functions: {
    "claimVestedTokens(address,uint256)": FunctionFragment;
    "getClaimAmount(uint256)": FunctionFragment;
    "getRemainingDuration(uint256)": FunctionFragment;
    "getUnlockTime(uint256)": FunctionFragment;
    "getVestingTime(uint256)": FunctionFragment;
    "vest(address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "claimVestedTokens",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUnlockTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVestingTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vest",
    values: [string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimVestedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnlockTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVestingTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vest", data: BytesLike): Result;

  events: {};
}

export class IVesting extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IVestingInterface;

  functions: {
    claimVestedTokens(
      recipient: string,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getClaimAmount(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getRemainingDuration(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getUnlockTime(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getVestingTime(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    vest(
      _recipient: string,
      _amount: BigNumberish,
      _vestingDuration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  claimVestedTokens(
    recipient: string,
    index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getClaimAmount(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRemainingDuration(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getUnlockTime(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getVestingTime(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  vest(
    _recipient: string,
    _amount: BigNumberish,
    _vestingDuration: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    claimVestedTokens(
      recipient: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getClaimAmount(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRemainingDuration(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUnlockTime(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVestingTime(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vest(
      _recipient: string,
      _amount: BigNumberish,
      _vestingDuration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    claimVestedTokens(
      recipient: string,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getClaimAmount(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRemainingDuration(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUnlockTime(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVestingTime(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vest(
      _recipient: string,
      _amount: BigNumberish,
      _vestingDuration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claimVestedTokens(
      recipient: string,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getClaimAmount(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRemainingDuration(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUnlockTime(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVestingTime(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vest(
      _recipient: string,
      _amount: BigNumberish,
      _vestingDuration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
